services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [
        'start-dev'
      ]
    ports:
      - 8080:8080
    volumes:
      - keycloak-storage:/keycloak

volumes:
  keycloak-storage: